"""Generated by `journey explore`. Review before committing."""

from __future__ import annotations

from urllib.parse import urlsplit
from uuid import uuid4

from journeysdk import branch, journey, step
from journeysdk.touchpoints.browser import JourneyBrowserPage, open_page


def _unique_email(prefix: str) -> str:
    return f"{prefix}-{uuid4().hex[:8]}@example.test"


def _assert_page_state(
    page: JourneyBrowserPage,
    *,
    expected_path: str | None = None,
    expected_title: str | None = None,
) -> None:
    if expected_path is not None:
        actual_path = urlsplit(page.url).path or "/"
        if actual_path != expected_path:
            raise AssertionError(f"Expected path {expected_path!r}, got {actual_path!r} from {page.url!r}.")
    if expected_title is not None:
        actual_title = page.title()
        if actual_title != expected_title:
            raise AssertionError(f"Expected title {expected_title!r}, got {actual_title!r}.")


def open_memosconf_registration_ops() -> JourneyBrowserPage:
    page = open_page('http://127.0.0.1:18081')
    timeout_ms = 30000
    page.wait_for_load_state("load", timeout=timeout_ms)
    _assert_page_state(page, expected_path='/', expected_title='MemosConf Registration Ops')
    return page


def fill_organizer_name(saved_page: JourneyBrowserPage) -> JourneyBrowserPage:
    """Enter organizer name in the registration form."""
    page = open_page(saved_page)
    timeout_ms = 30000

    def unique_email(prefix: str) -> str:
        return _unique_email(prefix)

    page.fill('[data-testid="organizer-name"]', 'John Smith', timeout=timeout_ms)
    page.wait_for_load_state("load", timeout=timeout_ms)
    _assert_page_state(page, expected_path='/', expected_title='MemosConf Registration Ops')
    return page


def fill_organizer_email(saved_page: JourneyBrowserPage) -> JourneyBrowserPage:
    """Enter organizer email address in the registration form."""
    page = open_page(saved_page)
    timeout_ms = 30000

    def unique_email(prefix: str) -> str:
        return _unique_email(prefix)

    page.fill('[data-testid="organizer-email"]', unique_email('organizer'), timeout=timeout_ms)
    page.wait_for_load_state("load", timeout=timeout_ms)
    _assert_page_state(page, expected_path='/', expected_title='MemosConf Registration Ops')
    return page


def fill_workspace_name(saved_page: JourneyBrowserPage) -> JourneyBrowserPage:
    """Enter workspace name for the conference."""
    page = open_page(saved_page)
    timeout_ms = 30000

    def unique_email(prefix: str) -> str:
        return _unique_email(prefix)

    page.fill('[data-testid="workspace-name"]', 'TechConf2024', timeout=timeout_ms)
    page.wait_for_load_state("load", timeout=timeout_ms)
    _assert_page_state(page, expected_path='/', expected_title='MemosConf Registration Ops')
    return page


def submit_registration(saved_page: JourneyBrowserPage) -> JourneyBrowserPage:
    """Click the Create conference workspace button to submit the registration form."""
    page = open_page(saved_page)
    timeout_ms = 30000

    def unique_email(prefix: str) -> str:
        return _unique_email(prefix)

    page.click('[data-testid="create-workspace"]', timeout=timeout_ms)
    page.wait_for_load_state('networkidle', timeout=timeout_ms)
    page.wait_for_load_state("load", timeout=timeout_ms)
    _assert_page_state(page, expected_path='/', expected_title='MemosConf Registration Ops')
    return page


@journey
def explored_agentic_loop_journey() -> None:
    open_memosconf_registration_ops_page = step(open_memosconf_registration_ops)
    if branch(replay_from=open_memosconf_registration_ops_page):
        fill_organizer_name_page = step(fill_organizer_name, open_memosconf_registration_ops_page)
    elif branch(replay_from=open_memosconf_registration_ops_page):
        fill_organizer_email_page = step(fill_organizer_email, open_memosconf_registration_ops_page)
    elif branch(replay_from=open_memosconf_registration_ops_page):
        fill_workspace_name_page = step(fill_workspace_name, open_memosconf_registration_ops_page)
    elif branch(replay_from=open_memosconf_registration_ops_page):
        submit_registration_page = step(submit_registration, open_memosconf_registration_ops_page)
