from __future__ import annotations

import pytest

import journeysdk.discover as discover_module
from journeysdk.discover import (
    ActionCapture,
    CandidateAction,
    DiscoverOptions,
    DiscoveredEdge,
    DiscoveredNode,
    PageSnapshot,
    ProbeSpec,
    _dedupe_candidates,
    _discover_json_state_url,
    _first_stable_identifier,
    _form_submit_candidate,
    _form_submit_candidates,
    _json_contains_value,
    _normalize_options,
    parse_candidate_actions,
    render_journey_source,
    validate_generated_source,
)


def _snapshot(url: str, title: str, text: str = "") -> PageSnapshot:
    return PageSnapshot(
        url=url,
        title=title,
        visible_text=text,
        semantic_dom="",
        signature=f"{url}|{title}|{text}",
    )


def test_parse_candidate_actions_accepts_unique_email_helper_and_code_fences() -> None:
    actions = parse_candidate_actions(
        """
        ```json
        {
          "actions": [
            {
              "name": "Create organizer workspace",
              "description": "Fill the organizer signup form.",
              "code": "page.locator(\\"[data-testid='organizer-email']\\").fill(unique_email(\\"organizer\\"), timeout=timeout_ms)"
            }
          ]
        }
        ```
        """
    )

    assert actions == [
        CandidateAction(
            name="Create organizer workspace",
            description="Fill the organizer signup form.",
            code=(
                "page.locator(\"[data-testid='organizer-email']\")"
                '.fill(unique_email("organizer"), timeout=timeout_ms)'
            ),
        )
    ]


def test_parse_candidate_actions_rejects_unsafe_python() -> None:
    with pytest.raises(RuntimeError, match="imports"):
        parse_candidate_actions(
            """
            {
              "actions": [
                {
                  "name": "steal files",
                  "description": "bad",
                  "code": "import os\\npage.goto('http://example.test', timeout=timeout_ms)"
                }
              ]
            }
            """
        )


def test_rendered_journey_source_compiles_with_branches() -> None:
    root = DiscoveredNode(
        node_id="root",
        start_url="http://example.test/",
        snapshot=_snapshot("http://example.test/", "Home", "Create Admin"),
        depth=0,
    )
    checkout = DiscoveredEdge(
        edge_id="checkout",
        parent=root,
        action=CandidateAction(
            name="Complete checkout",
            description="Complete attendee checkout.",
            code='page.get_by_text("Checkout").click(timeout=timeout_ms)',
        ),
        snapshot=_snapshot("http://example.test/checkout", "Checkout"),
    )
    admin = DiscoveredEdge(
        edge_id="admin",
        parent=root,
        action=CandidateAction(
            name="Open back office",
            description="Inspect back-office registrations.",
            code='page.get_by_text("Admin").click(timeout=timeout_ms)',
        ),
        snapshot=_snapshot("http://example.test/admin", "Back Office"),
    )
    root.edges.extend([checkout, admin])

    source = render_journey_source((root,), journey_name="discovered_demo")

    assert "if branch(replay_from=open_home_page):" in source
    assert "elif branch(replay_from=open_home_page):" in source
    assert "def complete_checkout" in source
    assert "def open_back_office" in source
    assert "Generated by `journey discover`" in source
    validate_generated_source(source, journey_name="discovered_demo")


def test_required_signup_form_becomes_one_submit_transition() -> None:
    candidate = _form_submit_candidate(
        {
            "action": "http://127.0.0.1:18081/signup",
            "fields": [
                {
                    "tag": "input",
                    "type": "text",
                    "selector": "[data-testid=\"organizer-name\"]",
                    "testid": "organizer-name",
                    "name": "full_name",
                    "label": "Organizer name",
                    "value": "Ada Morgan",
                    "required": True,
                },
                {
                    "tag": "input",
                    "type": "email",
                    "selector": "[data-testid=\"organizer-email\"]",
                    "testid": "organizer-email",
                    "name": "email",
                    "label": "Organizer email",
                    "value": "",
                    "required": True,
                },
                {
                    "tag": "input",
                    "type": "text",
                    "selector": "[data-testid=\"workspace-name\"]",
                    "testid": "workspace-name",
                    "name": "workspace_name",
                    "label": "Workspace name",
                    "value": "QA Conference",
                    "required": True,
                },
            ],
            "submit": {
                "selector": "[data-testid=\"create-workspace\"]",
                "testid": "create-workspace",
                "text": "Create conference workspace",
            },
        }
    )

    assert candidate is not None
    assert candidate.name == "create_workspace"
    assert candidate.code.count(".fill(") == 3
    assert '[data-testid="organizer-name"]' in candidate.code
    assert "unique_email(" in candidate.code
    assert "organizer-email" in candidate.code
    assert '[data-testid="workspace-name"]' in candidate.code
    assert 'page.locator(\'[data-testid="create-workspace"]\').click(timeout=timeout_ms)' in candidate.code


def test_checkout_select_and_submit_are_one_transition() -> None:
    candidate = _form_submit_candidate(
        {
            "action": "http://127.0.0.1:18081/checkout",
            "fields": [
                {
                    "tag": "input",
                    "type": "hidden",
                    "selector": "input[name=\"workspace_id\"]",
                    "name": "workspace_id",
                    "value": "1",
                },
                {
                    "tag": "input",
                    "type": "email",
                    "selector": "[data-testid=\"attendee-email\"]",
                    "testid": "attendee-email",
                    "name": "attendee_email",
                    "label": "Attendee email",
                    "required": True,
                },
                {
                    "tag": "select",
                    "selector": "[data-testid=\"ticket-type\"]",
                    "testid": "ticket-type",
                    "name": "ticket_type",
                    "options": [
                        {"value": "standard", "text": "Standard", "selected": True},
                        {"value": "vip", "text": "VIP", "selected": False},
                    ],
                },
            ],
            "submit": {
                "selector": "[data-testid=\"complete-registration\"]",
                "testid": "complete-registration",
                "text": "Complete registration",
            },
        }
    )

    assert candidate is not None
    assert candidate.name == "complete_registration"
    assert "attendee_email = unique_email(" in candidate.code
    assert "ticket_type = 'standard'" in candidate.code
    assert ".select_option(ticket_type, timeout=timeout_ms)" in candidate.code
    assert "workspace_id" not in candidate.code


def test_select_options_expand_into_bounded_transition_variants() -> None:
    candidates = _form_submit_candidates(
        {
            "action": "http://example.test/checkout",
            "fields": [
                {
                    "tag": "input",
                    "type": "email",
                    "selector": "[data-testid=\"buyer-email\"]",
                    "testid": "buyer-email",
                    "name": "buyer_email",
                    "label": "Buyer email",
                    "required": True,
                },
                {
                    "tag": "select",
                    "selector": "[data-testid=\"plan\"]",
                    "testid": "plan",
                    "name": "plan",
                    "label": "Plan",
                    "options": [
                        {"value": "", "text": "Choose a plan", "selected": False},
                        {"value": "standard", "text": "Standard pass", "selected": True},
                        {"value": "workshop", "text": "Workshop pass", "selected": False},
                        {"value": "team", "text": "Team pass", "selected": False},
                        {"value": "vip", "text": "VIP pass", "selected": False},
                    ],
                },
            ],
            "submit": {
                "selector": "[data-testid=\"complete-registration\"]",
                "testid": "complete-registration",
                "text": "Complete registration",
            },
        },
        max_variants_per_control=3,
    )

    assert [candidate.variant_value for candidate in candidates] == [
        "standard",
        "workshop",
        "team",
    ]
    assert [candidate.variant_label for candidate in candidates] == [
        "Standard pass",
        "Workshop pass",
        "Team pass",
    ]
    workshop_candidate = candidates[1]
    assert workshop_candidate.name == "complete_registration_workshop_pass"
    assert "plan = 'workshop'" in workshop_candidate.code
    assert ".select_option(plan, timeout=timeout_ms)" in workshop_candidate.code
    assert "vip" not in "\n".join(candidate.code for candidate in candidates)


def test_probe_helpers_match_identifiers_and_json_state_urls(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    assert _first_stable_identifier("Registration confirmed MC-ABC1234") == "MC-ABC1234"
    assert _first_stable_identifier("Provisioning configures seeded back-office state") is None
    assert _json_contains_value(
        {"registration": {"confirmation_code": "MC-ABC1234", "ticket_type": "workshop"}},
        "workshop",
    )

    fetched_urls: list[str] = []

    def fake_fetch(url: str, *, timeout: float) -> object | None:
        del timeout
        fetched_urls.append(url)
        if url.endswith("/api/state?confirmation_code=MC-ABC1234"):
            return {"confirmation_code": "MC-ABC1234"}
        return None

    monkeypatch.setattr(discover_module, "_fetch_json_if_ok", fake_fetch)

    assert (
        _discover_json_state_url("http://example.test/confirmation", "MC-ABC1234")
        == "http://example.test/api/state?confirmation_code={identifier}"
    )
    assert fetched_urls[0] == "http://example.test/api/state?confirmation_code=MC-ABC1234"


def test_generated_source_includes_discovered_probe_assertions() -> None:
    root = DiscoveredNode(
        node_id="root",
        start_url="http://example.test/",
        snapshot=_snapshot("http://example.test/", "Home", "Start"),
        depth=0,
    )
    confirmation = DiscoveredEdge(
        edge_id="confirmation",
        parent=root,
        action=CandidateAction(
            name="Complete checkout",
            description="Complete checkout and verify discovered evidence.",
            code="ticket_type = 'workshop'\npage.get_by_text('Complete').click(timeout=timeout_ms)",
            captures=(
                ActionCapture(
                    variable="ticket_type",
                    value="workshop",
                    kind="option",
                    label="Workshop pass",
                ),
            ),
        ),
        snapshot=_snapshot(
            "http://example.test/confirmation",
            "Confirmed",
            "Registration confirmed\nConfirmation code: MC-ABC1234",
        ),
        probes=(
            ProbeSpec(
                kind="json_state",
                url="http://example.test/api/state?confirmation_code={identifier}",
                description="same-origin JSON state contains the visible identifier",
            ),
            ProbeSpec(
                kind="email_evidence",
                url="http://127.0.0.1:18025",
                description="local email evidence contains the visible identifier",
            ),
            ProbeSpec(
                kind="webhook_evidence",
                url="http://127.0.0.1:19000",
                description="local webhook evidence contains the visible identifier",
            ),
        ),
    )
    root.edges.append(confirmation)

    source = render_journey_source((root,), journey_name="discovered_demo")

    assert "from journeysdk.touchpoints.http import http_request" in source
    assert "_first_visible_identifier(page, timeout_ms=timeout_ms)" in source
    assert "_wait_for_http_json(" in source
    assert "_wait_for_email_evidence(" in source
    assert "_wait_for_webhook_evidence(" in source
    assert "_journey_machine_expected_values" in source
    assert "ticket_type = 'workshop'" in source
    validate_generated_source(source, journey_name="discovered_demo")


def test_identifier_sanitization_and_candidate_dedupe() -> None:
    candidates = _dedupe_candidates(
        [
            CandidateAction("Open Admin", "first", "page.goto('http://example.test/admin')"),
            CandidateAction("Open Admin", "dupe", "page.goto('http://example.test/admin')"),
            CandidateAction("Open Checkout", "second", "page.goto('http://example.test/checkout')"),
        ]
    )

    assert [candidate.name for candidate in candidates] == ["Open Admin", "Open Checkout"]


def test_max_model_calls_validation() -> None:
    with pytest.raises(ValueError, match="--max-model-calls"):
        _normalize_options(
            DiscoverOptions(
                urls=("http://example.test",),
                max_model_calls=-1,
            )
        )


def test_discover_variant_and_probe_option_validation() -> None:
    with pytest.raises(ValueError, match="--max-variants-per-control"):
        _normalize_options(
            DiscoverOptions(
                urls=("http://example.test",),
                max_variants_per_control=0,
            )
        )

    with pytest.raises(ValueError, match="--side-effect-probes"):
        _normalize_options(
            DiscoverOptions(
                urls=("http://example.test",),
                side_effect_probes="invalid",  # type: ignore[arg-type]
            )
        )
